version: '3'

services:
  depth_service:
    build:
      context: ./depth_service
    ports:
      - "8001:8001"
    volumes:
      - ./depth_service:/app
    command: python manage.py runserver 0.0.0.0:8001

  llm_service:
    build:
      context: ./llm_service
    ports:
      - "8002:8002"
    volumes:
      - ./llm_service:/app
    command: python manage.py runserver 0.0.0.0:8002